### ISSUE TITLE
FEATURE REQUEST: Add support for Modrinth

### ISSUE THREAD

**Issue by sideeffectdk** [Senth/minecraft-mod-manager#11]
Great project @Senth! Besides CurseForge, there's now a second page that serves Minecraft mods.
And their API is very well documented: https://github.com/modrinth/labrinth/wiki
When implemented, it should be next to impossible to accidentally download a Forge version for Fabric, and vice versa.
There's even categories that show if the mod is useful on clients, servers or both.
Keep up the good work!

**Comment by Senth** [comment]
Thank you @sideeffectdk 🙂

Labrinth looks great. I'll definitely add support for it in the future™. Can't say when as I have many projects ongoing and working full-time. My guess is before 1.17 is released, but can't promise anything 🙂

**Comment by sideeffectdk** [comment]
No problem! Glad to help where I can (not a great python programmer, but I can do some beta testing if you need an extra pair of eyes and time permits)

**Comment by Senth** [comment]
Haven't manually tested that it works yet, but I've restructured the whole project and added lots of tests.

So it should support Modrinth now. It automatically searches both Modrinth and CurseForge and takes the latest release (according to published time) and uses it.

**Comment by sideeffectdk** [comment]
That is super awesome Senth!
Woop woop! I like reading your descriptions of all the issues and pull requests.
I'll get on testing it ASAP!
