### ISSUE TITLE
Cannot list any mods, outputs error

### ISSUE THREAD

**Issue by Mistyttm** [Senth/minecraft-mod-manager#126]
So I finally got the program to work after reading the wiki page. but none of the commands do anythin because they all throw these errors

`sqlite3.IntegrityError: UNIQUE constraint failed: mod.id`

`minecraft_mod_manager.core.errors.mod_already_exists.ModAlreadyExists:` Mod fireplacelib already found in the the db.`

I have no idea how to fix this

**Comment by Senth** [comment]
Hi Misty,

This can happen if you have multiple versions of the same mod inside the `mods` folder. Check in the mods folder for `fireplacelib` and see if you have multiple versions of it in there 🙂 

Closing this since it's a duplicate of #59,
