### ISSUE TITLE
Unable to find mod "dcch"

### ISSUE THREAD

**Issue by ezonius** [Senth/minecraft-mod-manager#135]
### Describe the bug 
MMM is unable to find mod "Don't Clear Chat History" from https://modrinth.com/mod/dcch/

`
dcch
    🔺 Mod not found on any site...
🔺 Mods not found
dcch
`

### Steps to reproduce
mmm configure dcch=modrinth:dcch
mmm --minecraft-version "1.17.1" --mod-loader fabric update dcch

### Expected Behavior

https://modrinth.com/mod/dcch/
MMM should update this mod, but is unable to find it.

### Info
 - OS: Windows 11
 - Python --version: 3.10.0
 - minecraft-mod-manager --version: 1.2.5

**Comment by Senth** [comment]
Hi @ezonius,

A very late answer, not even sure if you're using this any longer 😅 But this has now been fixed and will be released in v1.3.

I'm doing a big push during the weekend, maybe I can complete all the remaining issues for v1.3 🙂
