### ISSUE TITLE
CLI colorization issues

### ISSUE THREAD

**Issue by MrROBUST** [Senth/minecraft-mod-manager#141]
### Describe the bug 

The modloader suggestion highlight are missing closing color control symbol. This colorifies all following text, for example command input.

![изображение](https://user-images.githubusercontent.com/5786945/142729491-161e0fe2-8e17-42a0-a15a-3e5f8f21e1dd.png)

Windows ConHost receives lots of garbage symbols. Its probably better to add some way to turn off a colorization off, for example via environment variable or special version of the script.

![изображение](https://user-images.githubusercontent.com/5786945/142730114-1922abf3-7a3e-4680-b9d3-e3818f18f8f7.png)

**Comment by Senth** [comment]
Thanks for reporting the bug 🙂 

I have now fixed it and it will be released whenever `v1.3` comes out 🙂 

- There is also now an additional option `--no-color` to remove colored output.
- If it fails to print Unicode it will automatically disable both the color and remove all Unicode characters (like emojis)
