### ISSUE TITLE
mcman crashes with lazy-language-loader

### ISSUE THREAD

**Issue by Mistyttm** [Senth/minecraft-mod-manager#145]
### Describe the bug 
Minecraft Mod Manager crashes when attempting to download the lazy language loader mod

### Steps to reproduce
1. have lazy-language-loader in your mods folder
2. Then ran `mmm update -v 1.18 --beta --mod-loader fabric --verbose`

### Expected Behavior
Lazy language loader should be updated

### Info
 - OS: Windows 10 ver 21H1
 - Python --version: 3.10.0
 - minecraft-mod-manager --version: 1.2.4

**Comment by Senth** [comment]
Hi @Mistyttm,

Very late answer, but thanks for reporting! It's very helpful with these reports 🙂

Got around to fixing this bug now and should be released in [version 1.3](https://github.com/Senth/minecraft-mod-manager/milestone/4)
