### ISSUE TITLE
Add minimum python version into the documentation

### ISSUE THREAD

**Issue by IITFA** [Senth/minecraft-mod-manager#15]
I'm totally new to python scripts and pip, but I did:
pip3 install --user minecraft-mod-manager
(and tried pip2 and pip with same result)

and got this error:
Could not find a version that satisfies the requirement minecraft-mod-manager (from versions: )
No matching distribution found for minecraft-mod-manager

No idea how to fix this. Searching around doesn't seem to have any solutions.

**Comment by Senth** [comment]
Hmm, googled a bit and might've found something. Also tested on my server just to be sure it works.

Which python version do you use? The script requires at least python 3.8. Run: `python --version` 

I probably should add some info about the minimum python version in the readme 🙂

**Comment by IITFA** [comment]
The highest version of python in the stable Debian repos (the distro I'm on is based on Debian stable) is 3.7.3 apparently. Good thing I'm not new to compiling from source. For those not as familiar and are on a Debian stable distro, you could point them to this link:
https://linuxize.com/post/how-to-install-python-3-8-on-debian-10/

Yes, it might be a good idea to note the minimum python version.

**Comment by Senth** [comment]
Thanks for the suggestions and crash report 🙂 If you find any more in the future, it's better to add them to a new issue. I also don't get any notifications of edits so I can't respond to them as quickly.

Split the edits into two new issues. #16 and #17 🙂
