### ISSUE TITLE
Mcman not updating to 1.2.6

### ISSUE THREAD

**Issue by Mistyttm** [Senth/minecraft-mod-manager#160]
### Describe the bug 
No matter how many times I try, mcman refuses to update to 1.2.6, its stuck on 1.2.4

### Steps to reproduce
1. open comand prompt
2. ran `pip install --user --upgrade minecraft-mod-manager`
3. ran `mcman --version`

### Expected Behavior
The program should update to 1.2.6

### Info
 - OS: Windows 
 - Python --version: 3.10.0
 - minecraft-mod-manager --version: 1.2.4

**Comment by Senth** [comment]
Hi, thanks for reporting 🙂 

I have a fix for this, but I will release 1.2.7 once #150 is fixed (hopefully later today) since that stops the program.
