### ISSUE TITLE
url wrong in 'Curseforge has been disabled' message

### ISSUE THREAD

**Issue by TemDevz** [Senth/minecraft-mod-manager#191]
![image](https://user-images.githubusercontent.com/25987110/178035017-6c736070-1efc-4a8c-9e50-53ef68f2c2d0.png)

link should be `https://github.com/Senth/minecraft-mod-manager`
not `https://github.com/Senth/minecraft_mod_manager`

**Comment by Senth** [comment]
Thanks @TemDevz! I'll be sure to update it 🙂
