### ISSUE TITLE
Can't download mods that doesn't specify mod-loader from CurseForge

### ISSUE THREAD

**Issue by Senth** [Senth/minecraft-mod-manager#35]
### Problem
Can't install or update mods that don't specify a mod-loader. For example `jei`

Running `minecraft-mod-manager install jei` returns "No new version found"

### Solution
If no mod-loader version is specified in the files/version, it shouldn't be filtered out.

**Comment by coldino** [comment]
Messing about with this locally:
```diff
    @staticmethod
    def _is_filtered_by_mod_loader(prev: ModLoaders, version: VersionInfo) -> bool:
        if config.filter.loader == ModLoaders.unknown:
-            if prev != ModLoaders.unknown:
+            if prev != ModLoaders.unknown and version.mod_loaders:
                return prev not in version.mod_loaders
            return False
        return config.filter.loader not in version.mod_loaders
```
...seems to work. Not ideal but I don't see a better method currently.
