### ISSUE TITLE
v2 - The GUI Update

### ISSUE THREAD

**Issue by Senth** [Senth/minecraft-mod-manager#38]
This issue contains all high-level information about the next version (v2 - the GUI Update).

## Problem with the CLI
Using the command line is unintuitive for people that aren't used to using command lines. To make this script appeal to the masses it needs to have a GUI that works intuitively.

## Vision
It should take less than one minute for everyone to update mods from the very first run of the program. And it should just work.

## Hurdles
While it's a high vision to have, it should work in most scenarios. But there are some hurdles. Mainly that CurseForge doesn't have a good search engine. But that might be fixed by using alternative search engines #91

## MVP Features
- Automatically find all MC instances (MultiMC, Minecraft Launcher, Twitch App)
  - Also search in the configurable path (only available as an option through the cfg from start)
- Show all MC instances and mods
  - Automatically detect MC version
  - List mods for that instance
  - See which have an available update
- One button to update all mods across all instances
- Search and install mods across CurseForge and Modrinth (more to come?)
- Flag specific mods to not update (sometimes you just want to have a specific version of a mod)
- Enable/Disable mods. This does just enable and disable mods.
- Incompatible mods
  - Automatically set mods as incompatible when an MC version has been changed (unless it's still compatible)
  - When updating check for updates on incompatible mods

## Future Features/Ideas
These are not part of the v2 update. but logged here to remember them.
- Check the compatibility of an instance if you were to upgrade to a newer MC version
- Show more information about mods
- Show number of updates per tab
- Settings window
- Stability per mod
- Configure locations to search for MC instances?

## Progress Status
Below you can see the status of all v2 tasks. You can also check out [v2 Project site](https://github.com/Senth/minecraft-mod-manager/projects/1) for a Kanban view of the project.

### GUI
- #96 
- #97
- #98
- #99
- #100
- #101
- #102
- #103
- #104
- #105
- #106
- #107

### CLI
- #108
- #109
- #110
- #111
- #112

### GUI/CLI/Logic
- #154 
- #75
- #113

### Logic
- #114
- #91
- #115
- #116
- #117
- #26
- #89 
- #55 
- #118
- #119
- #120

### Packaging
- #39

### Wiki
- #70
- Probably more... 

## DoD
When v2 is released.

**Comment by sideeffectdk** [comment]
Great and ambitious goal Senth!
If you want to shoot for the stars, then take a look at the amazing mod manager for Kerbal Space Program: [CKAN](https://github.com/KSP-CKAN/CKAN) .
Maybe there's some inspiration to get from there.
They have a thorough backend for caching mods from several sources, and the GUI tells you about conflicts/mod versions for different game versions/recommended extra mods.
Your MVP features is a great set of starting features. I know people would appreciate a good Minecraft mod manager with a GUI, and will certainly spread the word about yours. Happy coding Senth

**Comment by Senth** [comment]
Thank you, sideeffectdk 😃 

And thanks for sharing CKAN, if you hadn't I probably just would've started implementing something without checking what's already out there for other games. It also inspired me to check out some other games and see how they manage mods, what works great and what doesn't work so well.

I have an idea to released this somewhere before Minecraft 1.18 is released. Hopefully, I can keep that schedule 🙂

**Comment by Senth** [comment]
Restructuring this issue to be the milestone and documentation of v2 the GUI update.
