### ISSUE TITLE
Avoiding source file releases

### ISSUE THREAD

**Issue by coldino** [Senth/minecraft-mod-manager#40]
Not sure how to identify these, but sometimes source-file releases are picked over useful files... e.g. <https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/3202662>

**Comment by Senth** [comment]
Hmm, tried to reproduce. But from what I can tell the files I get when using CurseForge API only contains the mod and no src files. So unless you're using a very old version of `minecraft-mod-manager`  that is not the case.

I did, however, notice that it tried to download from Modrinth first, and it seems the author only created the mod page but doesn't upload any versions there. So it finds that the mod exists, but doesn't download any version. And then it doesn't try to download anything from Curse.

Issue #27 takes care of that, but I added a bug label to it to prioritize it.

If you find another mod this happens with, feel free to comment here and I'll reopen the issue 🙂
