### ISSUE TITLE
Show a better message when failing to install a mod because it's filtered

### ISSUE THREAD

**Issue by itsmeboy0** [Senth/minecraft-mod-manager#58]
I am trying to install [Inventory HUD+](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge) by doing `minecraft-mod-manager install inventory-hud-forge` and it silently exits with this output:

```
inventory-hud-forge
```

It doesn't seem to be installed after that.

**Comment by Senth** [comment]
Will look into this whenever I get time

**Comment by Senth** [comment]
There doesn't seem to be a stable Fabric release of inventory-hud-forge. To install it you have to run

```
minecraft-mod-manager install inventory-hud-forge --beta
```

I will add some better message saying why it wasn't found, so it doesn't fail silently.

**Comment by Senth** [comment]
Will soon create a PR, the fix will look something like this:
![image](https://user-images.githubusercontent.com/2499370/121800845-66ccde00-cc34-11eb-82fa-76f8b07cc809.png)

Or like this if you run with `--verbose`
![image](https://user-images.githubusercontent.com/2499370/121800912-b7443b80-cc34-11eb-9642-4daf482f3065.png)
