### ISSUE TITLE
Tool crashes with some mods

### ISSUE THREAD

**Issue by RJWadley** [Senth/minecraft-mod-manager#60]
Fabric capes mod throws `UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 194-195: invalid continuation byte`
The manager will always crash if this mod is present

To reproduce, run `minecraft-mod-manager --mod-loader fabric install capes`
Then, run `minecraft-mod-manager list` to see the crash

Encountered on Ubuntu Linux

**Comment by Senth** [comment]
Hi @RJWadley,

Thanks a lot for reporting the bug 🙂 Will see if I can fix the bug this weekend since it seems like a simple fix (famous last words 😅) Can't promise anything though.

**Comment by Senth** [comment]
Got some extra time today, so fixed this bug 🙂  I will fix a bunch of other bugs before releasing the next version this Sunday.

**Comment by RJWadley** [comment]
I think this is probably a related issue with the same symptom.

`minecraft-mod-manager install shulkerboxtooltip`

throws:
`simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

using version 1.2.1

**Comment by Senth** [comment]
Yeah, think I know the problem. I fixed reading JSON from the `.jar` file, but this error is thrown when reading the JSON response from Curse/Modrinth API. I will apply the same fix over there 🙂

**Comment by Senth** [comment]
@RJWadley Hmm, I'm having some trouble reproducing this. When I run `minecraft-mod-manager install shulkerboxtooltip` it installs correctly.

Would you mind supplying me with your OS and `python --version`? Feel free to answer here or in #79

**Comment by Senth** [comment]
Hmm, actually you can simply test the version `1.2.2` of `minecraft-mod-manager` since I think that should fix it, although not entirely sure.

**Comment by RJWadley** [comment]
The issue seemed to be that the database was corrupt. Deleting the database fixed the issue.

**Comment by Senth** [comment]
@RJWadley, do you by any chance still have the corrupt database in your Recycle bin?

I changed the database structure in 1.2.0 and implemented some migration logic and tests but probably missed one or a couple of cases. Would be really valuable to have that 🙂 

There's no personal information saved in the database, only what version of the database, and mods (for example):

| mod_id | site | site_id | site_slug | upload_time | active |
| --- | --- | --- | --- | --- | --- |
| dynmap | curse | 467864 | dynmapforge | 12345678 | 1 |
