### ISSUE TITLE
Sometimes permanently deletes mods

### ISSUE THREAD

**Issue by RJWadley** [Senth/minecraft-mod-manager#81]
### Describe the bug 
Sometimes the tool deletes mods when it definitely should not. Over time this effect can delete almost an entire mods folder.

### Steps to reproduce
1. Download the sample mods folder from the following link. There should be 40 mods in the archive. [Sample Mods](https://drive.google.com/file/d/1qoBmoHcNow0gNDMlgTlDx1ib7HbrxJMB/view?usp=sharing)
2. Extract to a folder (doesn't need to be minecraft's actual mods folder, just somewhere the tool can run)
3. Run `minecraft-mod-manager list` and ensure the tool can see all 40 mods
4. Run `minecraft-mod-manager update`
5. Repeat step 4 until something seems off (should only take 2 or 3 runs to become rather obvious that some mods are gone)

### Expected Behavior
After step 4, all 40 mods should remain intact

### Info
 - OS: Ubuntu Linux 18.04
 - Python --version: 3.8.5
 - minecraft-mod-manager --version: 1.2.2

**Comment by Senth** [comment]
Thanks, will look into this in a few hours!

**Comment by Senth** [comment]
Sorry if that caused you some headaches. I know it would for me when I have the server since it's hard to know which mods you had or not. The fix should be out a few minutes after this issue is closed.
